config/routes.rb
Nahual::Application.routes.draw do
  devise_for :users

  root :to => 'inscriptions#index'


  resources :disciplines do
    member do
      post 'disable_all'
      post 'enable_all'
    end
  end

  resources :users, :only => [:index, :destroy, :edit, :update] do
    resources :payments, :only => [:new, :create]
    collection do
      get 'credits', to: 'users#credits'
      post 'reset', to: 'users#reset'
      post 'set_reset', to: 'users#set_reset'
      get 'reset_search', to: 'users#reset_search'
      get 'stop_impersonating'
    end
    member do
      get 'impersonate'
      post 'certificate'
    end
  end

  resources :payments, only: [:edit, :update]

  resources :past_shifts, :only => [:index, :show]

  resources :shifts do
    collection do
      get 'next_class'
    end
  end

  resources :payments, :only => [:index, :destroy] do
    collection do
      get 'total_payments', to: 'payments#total_payments'
    end
  end

  resources :rookies do
    collection do
      get 'new_in_shift/:shift_id', to: 'rookies#new_in_shift', as: 'new_in_shift'
    end
    member do
      post 'attended'
    end
  end

  resources :stats, :only => [:index] do
    collection do
      get 'month_inscriptions_chart', to: 'stats#month_inscriptions_chart', as: 'month_inscriptions_chart'
    end
  end

  resources :inscriptions
  post 'incriptions/:id/attended', to: 'inscriptions#attended'

  resources :messages
  resources :packs

  get 'check_pending_messages', to: 'application#check_pending_messages'
end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  has_many :shifts

  has_many :user_disciplines
  has_many :users, through: :user_disciplines

  validates_presence_of :name
  validates_presence_of :color
  validates_presence_of :font_color

  before_validation :set_default_colors

  private

  def set_default_colors
    self.color = '#fafafa' if self.color.blank?
    self.font_color = '#000105' if self.font_color.blank?
  end

end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController

  def index
    respond_to do |format|
      format.html
      format.json { render json: DisciplineDatatable.new(view_context) }
    end
  end

  def new
    @discipline = Discipline.new
  end

  def create
    @discipline = Discipline.new(discipline_params)
    if @discipline.save
      redirect_to disciplines_path, success: "La nueva disciplina #{@discipline.name} a sido creada."
    else
      render :new
    end
  end

  def edit
    @discipline = Discipline.find(params[:id])
  end

  def update
    @discipline = Discipline.find(params[:id])
    @discipline.update_attributes!(discipline_params)
    redirect_to disciplines_path, success: "#{@discipline.name} a sido modificada."

  end

  def enable_all
    discipline = Discipline.find(params[:id])
    User.find_each do |user|
      user.disciplines << discipline unless user.disciplines.include?(discipline)
    end
    redirect_to disciplines_path, success: "Todos los usuarios pueden inscribirse a #{discipline.name}"

  end

  def disable_all
    discipline = Discipline.find(params[:id])
    User.find_each do |user|
      user.disciplines.delete(discipline) if user.disciplines.include?(discipline)
    end
    redirect_to disciplines_path, success: "Ningún usuario puede inscribirse a #{discipline.name}"
  end

  def destroy
    discipline = Discipline.find(params[:id])
    if discipline.shifts.count > 0
      redirect_to disciplines_path, error: "#{discipline.name} no puede ser borrada porque es usada para clases."
    elsif discipline.users.count > 0
      redirect_to disciplines_path, error: "#{discipline.name} no puede ser borrada porque es usada por usuarios."
    else
      discipline.destroy
      redirect_to disciplines_path, success: "#{discipline.name} fue borrada."

    end
  end

  def discipline_params
    params.require(:discipline).permit(:name, :default, :color, :font_color)
  end

end

app/views/disciplines/_form.html.erb
<%= simple_form_for(@discipline) do |f| %>
  <%= f.input :name, autofocus: true  %>
  <%= f.input :default %>
  <%= f.input :color, as: :minicolors, input_html: {data: {minicolors: {theme: :bootstrap}}} %>
  <%= f.input :font_color, as: :minicolors, input_html: {data: {minicolors: {theme: :bootstrap}}} %>
  <%= f.submit 'Guardar', data: { disable_with: "Procesando..." }, class: "btn btn-primary" %>
  <%= link_to "Volver", :back, class: "btn btn-default" %>
<% end %>

app/views/disciplines/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Modificar Clase</h4>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/disciplines/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Disciplinas</h4>
  </div>
  <div class="panel-body">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= link_to "Agregar una nueva Disciplina", new_discipline_path, class: 'btn btn-primary' %>
      </div>
    </div>
    <div class="table-responsive">
      <table id="disciplines-table" class="table table-striped table-bordered" cellspacing="0" width="100%" data-source="<%= disciplines_path(format: :json) %>">
        <thead>
        <tr>
          <th>Disciplina</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/disciplines/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Nueva Disciplina</h4>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>