config/routes.rb
Nahual::Application.routes.draw do
  devise_for :users

  root :to => 'inscriptions#index'


  resources :disciplines do
    member do
      post 'disable_all'
      post 'enable_all'
    end
  end

  resources :users, :only => [:index, :destroy, :edit, :update] do
    resources :payments, :only => [:new, :create]
    collection do
      get 'credits', to: 'users#credits'
      post 'reset', to: 'users#reset'
      post 'set_reset', to: 'users#set_reset'
      get 'reset_search', to: 'users#reset_search'
      get 'stop_impersonating'
    end
    member do
      get 'impersonate'
      post 'certificate'
    end
  end

  resources :payments, only: [:edit, :update]

  resources :past_shifts, :only => [:index, :show]

  resources :shifts do
    collection do
      get 'next_class'
    end
  end

  resources :payments, :only => [:index, :destroy] do
    collection do
      get 'total_payments', to: 'payments#total_payments'
    end
  end

  resources :rookies do
    collection do
      get 'new_in_shift/:shift_id', to: 'rookies#new_in_shift', as: 'new_in_shift'
    end
    member do
      post 'attended'
    end
  end

  resources :stats, :only => [:index] do
    collection do
      get 'month_inscriptions_chart', to: 'stats#month_inscriptions_chart', as: 'month_inscriptions_chart'
    end
  end

  resources :inscriptions
  post 'incriptions/:id/attended', to: 'inscriptions#attended'

  resources :messages
  resources :packs

  get 'check_pending_messages', to: 'application#check_pending_messages'
end

app/views/shared/_nav_guest.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand no-padding" href="#"><img src="<%= image_url('logo_small.png') %>" /></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav nav-pills navbar-right">
        <li>
          <%= link_to new_user_registration_path do %>
            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>Registrarse
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>Ingresar
          <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/shared/_nav_signed_in.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img src="<%= image_url('logo_small.png') %>" /></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav nav-pills navbar-left">
        <li role="presentation"><%= link_to 'Turnos', inscriptions_path %></li>
      </ul>

      <ul class="nav nav-pills navbar-right">
        <li>
          <%= link_to edit_user_registration_path do %>
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span><span data-toggle="tooltip" data-placement="bottom" title="Cambiar mis datos, contraseña, etc."><%= current_user.full_name %></span>
          <% end %>
        </li>
        <li>
          <%= link_to edit_user_registration_path do %>
            <span class="glyphicon glyphicon-credit-card" aria-hidden="true"></span><span id="user-credit" data-toggle="tooltip" data-placement="bottom" title="Créditos disponibles"><%= current_user.credit.to_s %></span>
          <% end %>
        </li>
        <% if current_user.credit > 0 %>
          <li>
            <%= link_to '#' do %>
              <span class="glyphicon glyphicon-time" aria-hidden="true"></span><span id="user-credit-end" data-toggle="tooltip" data-placement="bottom" title="Fecha de vencimiento de los créditos"><%= I18n.l(current_user.last_credit_end_date, format: '%a, %e %b, %Y') %></span>
            <% end %>
          </li>
        <% end %>

        <% if current_user == true_user %>
          <li>
            <%= link_to destroy_user_session_path, :method => :delete do %>
              <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>Cerrar Sesión
            <% end %>
          </li>
        <% elsif true_user.admin? %>
          <li>
            <%= link_to stop_impersonating_users_path do %>
              <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>Volver a Admin
            <% end %>
          </li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/shared/_nav_signed_in_admin.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img src="<%= image_url('logo_small.png') %>" /></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav nav-pills navbar-left">
        <li role="presentation"><%= link_to 'Próxima clase', '#', id: 'next_class' %></li>
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            Clientes <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li role="presentation"><%= link_to 'Listado', users_path %></li>
            <li role="presentation"><%= link_to 'Reseteo de créditos', credits_users_path %></li>
          </ul>
        </li>
        <li role="presentation"><%= link_to 'Inscripciones manuales', rookies_path %></li>
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            Consulta <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li role="presentation"><%= link_to 'Pagos', payments_path %></li>
            <li role="presentation"><%= link_to 'Clases', past_shifts_path %></li>
            <li role="presentation"><%= link_to 'Estadísticas', stats_path %></li>
          </ul>
        </li>
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            Configuración <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li role="presentation"><%= link_to 'Clases', shifts_path %></li>
            <li role="presentation"><%= link_to 'Packs de Clases', packs_path %></li>
            <li role="presentation"><%= link_to 'Notificaciones', messages_path %></li>
            <li role="presentation"><%= link_to 'Disciplinas', disciplines_path %></li>
          </ul>
        </li>

      </ul>

      <ul class="nav nav-pills navbar-right">
        <li>
          <%= link_to edit_user_registration_path do %>
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span><%= current_user.full_name %>
          <% end %>
        </li>

        <% unless current_user.admin? %>
          <%= link_to edit_user_registration_path do %>
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span><%= current_user.credit.to_s %>
          <% end %>
        <% end %>

        <li>
          <%= link_to destroy_user_session_path, :method => :delete do %>
            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>Cerrar Sesión
          <% end %>
        </li>


      </ul>
    </div><!-- /.navbar-collapse -->
</nav>