config/routes.rb
Nahual::Application.routes.draw do
  devise_for :users

  root :to => 'inscriptions#index'


  resources :disciplines do
    member do
      post 'disable_all'
      post 'enable_all'
    end
  end

  resources :users, :only => [:index, :destroy, :edit, :update] do
    resources :payments, :only => [:new, :create]
    collection do
      get 'credits', to: 'users#credits'
      post 'reset', to: 'users#reset'
      post 'set_reset', to: 'users#set_reset'
      get 'reset_search', to: 'users#reset_search'
      get 'stop_impersonating'
    end
    member do
      get 'impersonate'
      post 'certificate'
    end
  end

  resources :payments, only: [:edit, :update]

  resources :past_shifts, :only => [:index, :show]

  resources :shifts do
    collection do
      get 'next_class'
    end
  end

  resources :payments, :only => [:index, :destroy] do
    collection do
      get 'total_payments', to: 'payments#total_payments'
    end
  end

  resources :rookies do
    collection do
      get 'new_in_shift/:shift_id', to: 'rookies#new_in_shift', as: 'new_in_shift'
    end
    member do
      post 'attended'
    end
  end

  resources :stats, :only => [:index] do
    collection do
      get 'month_inscriptions_chart', to: 'stats#month_inscriptions_chart', as: 'month_inscriptions_chart'
    end
  end

  resources :inscriptions
  post 'incriptions/:id/attended', to: 'inscriptions#attended'

  resources :messages
  resources :packs

  get 'check_pending_messages', to: 'application#check_pending_messages'
end

app/models/shift.rb
class Shift < ActiveRecord::Base

  acts_as_paranoid

  belongs_to :instructor
  belongs_to :discipline
  has_many :inscriptions
  has_many :users, through: :inscriptions
  has_many :rookies

  STATUS = {:open => 'abierta', :close => 'cerrada', :full => 'completa'}

  DEFAULT_SHIFT_DURATION = 1
  MARTIN_BIANCULLI_ID = 2
  MARCELO_PERRETTA_ID =  41
  IVAN_TREVISAN_ID = 7
  ALLOWED_USERS = [MARTIN_BIANCULLI_ID, MARCELO_PERRETTA_ID, IVAN_TREVISAN_ID]

  DISABLE_TEXT_COLOR = '#CCCCCC'
  DISABLE_BG_COLOR = '#EBEBE4'

  before_destroy :remove_inscriptions

  validates_presence_of :week_day, :start_time, :end_time, :max_attendants, :open_inscription, :close_inscription, :instructor, :discipline, :cancel_inscription
  validates_uniqueness_of :start_time, :scope => [:week_day]

  def self.with_discipline_and_instructor
    preload(:discipline, :instructor)
  end

  def self.with_shift_dates(start_date = Chronic.parse("now").strftime('%F %R'))
    select(
      "IF (
        '#{start_date}' > STR_TO_DATE(CONCAT(DATE_FORMAT(DATE_ADD('#{start_date}', interval (week_day - DAYOFWEEK('#{start_date}')) day), '%Y-%m-%d'),' ', start_time), '%Y-%m-%d %H:%i'),
        CONCAT(DATE_FORMAT(DATE_ADD('#{start_date}', interval (7 + week_day - DAYOFWEEK('#{start_date}')) day), '%Y-%m-%d'),' ', start_time),
        CONCAT(DATE_FORMAT(DATE_ADD('#{start_date}', interval (week_day - DAYOFWEEK('#{start_date}')) day), '%Y-%m-%d'),' ', start_time)
      ) as next_shift, shifts.*"
    )
  end

  ##
  # @return The next class of all the shift collection in the database
  #
  def self.get_next_class
    Shift.where(
        'week_day >= ? AND end_time > ?',
        Chronic.parse("now").strftime('%w').to_i + 1,
        Chronic.parse("now").strftime('%H:%M')
    ).order("week_day ASC, end_time ASC").limit(1).first
  end

  def as_json(options = {})
    raise ArgumentException unless options[:user].present?
    user = options[:user]
    selectable = available_for_enroll?(user) || available_for_cancel?(user)
    booked = !user_inscription(user).nil?
    end_date = next_fixed_shift + (end_time - start_time).second

    closed_unattended = !selectable && booked && Chronic.parse('now') < end_date
    description = "Coach: #{instructor.first_name}"
    description += '<br /> No puede liberarse' if closed_unattended

    {
      id: id,
      title: discipline.name,
      start: next_fixed_shift.strftime('%F %R'),
      end: end_date.strftime('%F %R'),
      color: selectable || closed_unattended ? discipline.color : DISABLE_BG_COLOR,
      textColor: selectable || closed_unattended ? discipline.font_color : DISABLE_TEXT_COLOR,
      description: description,
      className: 'calendar-text',
      status: status, # just to show the status
      open: selectable,
      deadline: cancel_inscription,
      booked: booked,
      needs_confirmation: needs_confirmation?
    }
  end

  ##
  # @return The specific date of the next class of this shift
  #
  def next_fixed_shift
    @next_shift_date ||= Chronic.parse(try(:next_shift)) || Chronic.parse(Shift.with_shift_dates.where(id: id).first.next_shift)
  end

  ##
  # @return [ActiveRecord::Relation] inscriptions for the next class of this shift
  #
  def next_fixed_shift_users
    inscriptions.where(:shift_date => next_fixed_shift)
  end

  def next_fixed_shift_rookies
    rookies.where(:shift_date => next_fixed_shift)
  end

  ##
  # @return Number of inscriptions for the next shift
  #
  def next_fixed_shift_count
    count = $redis.cache(:key => redis_key) { next_fixed_shift_count_db }
    count.to_i
  end

  def enroll_next_shift(user)
    user.update_credits!
    if available_for_enroll?(user.reload)
      self.inscriptions << Inscription.create({:user_id => user.id, :shift_date => next_fixed_shift})
      $redis.cache(:key => redis_key, :recalculate => true) { next_fixed_shift_count_db }
    else
      self.errors[:base] << "No es posible anotarse a la clase, ya está anotado, está cerrada o completa"
      false
    end
  end

  def needs_confirmation?
    Chronic.parse("now") > Chronic.parse("#{cancel_inscription} hours ago", :now => next_fixed_shift)
  end

  def cancel_next_shift(user)
    if available_for_cancel?(user.reload)
      self.inscriptions.where({:user_id => user.id, :shift_date => next_fixed_shift}).first.destroy
      $redis.cache(:key => redis_key, :recalculate => true) { next_fixed_shift_count_db }
    else
      self.errors[:base] << "No es posible liberar la clase, ya está cerrada o no está anotado"
      false
    end
  end

  def enroll_next_shift_rooky(rooky)
    if self.available_for_try?
      rooky.shift_date ||= next_fixed_shift
      rooky.shift_id ||= id
      if rooky.save
        $redis.cache(:key => redis_key, :recalculate => true) { next_fixed_shift_count_db }
        return true
      end
    else
      self.errors[:base] << "No es posible anotarse a la clase. Salga del sistema y vuelva a ingresar para compruebar que tenga créditos suficientes y que la clase no se encuentre cerrada o completa"
    end
    return false
  end

  def cancel_inscription_rooky
    $redis.cache(:key => redis_key, :recalculate => true) { next_fixed_shift_count_db }
  end

  def exceptions?(user)
    ALLOWED_USERS.include?(user.id) && status != STATUS[:full] && user_inscription(user).nil? && user.credit > 0 && user.disciplines.include?(discipline)
  end

  ##
  # @return [Boolean] if the shift is available to enroll an anonymous user for a free class or not
  #
  def available_for_try?
    status != STATUS[:full]
  end

  ##
  # @return nil or the inscription record of the user
  #
  def user_inscription(user)
    user.inscriptions.find { |i| i.shift_date == next_fixed_shift }
  end

  def another_today_inscription?(user)
    !user.inscriptions.find { |i| i.shift_date.strftime('%D') == next_fixed_shift.strftime('%D') && i.shift.discipline == discipline }.nil?
  end

  def day_and_time
    "#{I18n.t('date.day_names')[week_day.to_i - 1].capitalize} #{start_time.strftime('%H:%M')} hs."
  end

  ##
  # When removing a shift we remove the inscriptions to that shift and refund the credits
  #
  def remove_inscriptions
    next_fixed_shift_users.destroy_all
  end

  # current_time = 10:00
  # 12:00 - 3 = 9:00 => 9:00 < 10:00 => cerrada
  # start_time - close_inscription < current time => cerrada
  #
  # current_time = 7:00
  # 12:00 - 10 = 2:00 < 7:00 => abierta (and the cerrada is not met)
  # start_time - open_inscription < current_time => abierta
  def status
    return STATUS[:full] if next_fixed_shift_count >= max_attendants

    hours_diff = (next_fixed_shift - Chronic.parse("now")) / 3600
    if hours_diff > close_inscription && hours_diff < open_inscription
      STATUS[:open]
    else
      STATUS[:close]
    end

  end

private

  ##
  # @param user [User] the user we would like to enroll
  # @return [Boolean] if the shift is available to enroll a user or not
  #
  def available_for_enroll?(user)
    return true if exceptions?(user)
    return false if user.pack.present? && !user.pack.shifts.include?(self)
    ( status == STATUS[:open] && user_inscription(user).nil? && user.credit > 0 && user.disciplines.include?(discipline) )
  end

  def available_for_cancel?(user)
    user_inscription(user).present? && (status != STATUS[:close] && !needs_confirmation? || ALLOWED_USERS.include?(user.id) )
  end

  def next_fixed_shift_count_db
    next_fixed_shift_users.count + next_fixed_shift_rookies.count
  end

  def redis_key
    "#{next_fixed_shift.to_s.gsub(/\s/, '_')}_#{id}"
  end

end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController

  def next_class
    shift = Shift.get_next_class
    if shift.present?
      render json: shift.id
    else
      head status: :not_found
    end
  end

  def index
    respond_to do |format|
      format.html
      format.json { render json: ShiftDatatable.new(view_context) }
    end
  end

  def new
    @shift = Shift.new
  end

  def create
    deleted_shifts = Shift.only_deleted.where(start_time: shift_params[:start_time], week_day: shift_params[:week_day])
    if deleted_shifts.present?
      @shift = deleted_shifts.first.restore
      @shift.assign_attributes(shift_params)
    else
      @shift = Shift.new(shift_params)
    end
    if @shift.save
      redirect_to shifts_url, success: 'Nueva Clase creada.'
    else
      render action: "new"
    end
  end

  def show
    @shift = Shift.with_discipline_and_instructor.with_shift_dates(DateTime.parse(Chronic.parse("now").strftime('%F %R')).beginning_of_hour).where(id: params[:id]).first
  end

  def edit
    @shift = Shift.find(params[:id])
  end

  def update
    @shift = Shift.find(params[:id])
    if @shift.update_attributes(shift_params)
      redirect_to shifts_url, success: 'Clase actualizada.'
    else
      render action: "edit"
    end
  end

  def destroy
    @shift = Shift.with_shift_dates.where(id: params[:id]).first
    if @shift.destroy
      flash[:success] = "La Clase del #{@shift.day_and_time} fue eliminada correctamente."
    else
      flash[:error] = @shift.errors.to_a.join("<br />")
    end
    redirect_to shifts_url
  end

  private

    def format_date_for_alerts
      "<b>#{I18n.l(@shift.next_fixed_shift, :format => '%A, %e de %B %H:%M hs.')}</b>"
    end

    def shift_params
      params[:shift][:start_time] = Time.zone.local(
          params[:shift]['start_time(1i)'],
          params[:shift]['start_time(2i)'],
          params[:shift]['start_time(3i)'],
          params[:shift]['start_time(4i)'],
          params[:shift]['start_time(5i)']
      ).to_s(:time) if params[:shift]['start_time(4i)'].present?
      params[:shift][:end_time] = Time.zone.local(
          params[:shift]['end_time(1i)'],
          params[:shift]['end_time(2i)'],
          params[:shift]['end_time(3i)'],
          params[:shift]['end_time(4i)'],
          params[:shift]['end_time(5i)']
      ).to_s(:time) if params[:shift]['end_time(4i)'].present?
      params.require(:shift).permit(:week_day, :start_time, :end_time, :max_attendants, :open_inscription, :close_inscription, :instructor_id, :discipline_id, :cancel_inscription)
    end

end

app/views/shifts/_form.html.erb
<%= simple_form_for(@shift) do |f| %>
  <%= f.input :week_day, collection: t('date.day_names').zip((1..7).to_a), include_blank: false, autofocus: true %>
  <%= f.input :start_time %>
  <%= f.input :end_time %>
  <%= f.input :max_attendants %>
  <%= f.input :open_inscription, hint: 'cantidad de horas antes de la clase en que se abre la inscripción' %>
  <%= f.input :close_inscription, hint: 'cantidad de horas antes de la clase en que se cierra la inscripción' %>
  <%= f.input :cancel_inscription, hint: 'cantidad de horas antes de la clase en que se deshabilita la opción de liberar' %>
  <%= f.association :instructor, label_method: :full_name, include_blank: false %>
  <%= f.association :discipline, include_blank: false %>

  <%= f.submit 'Guardar', data: { disable_with: "Procesando..." }, class: "btn btn-primary" %>
  <%= link_to "Volver", :back, class: "btn btn-default" %>
<% end %>

app/views/shifts/_user_list.html.erb
<% if users.count > 0 %>
  <div class="panel panel-default table-responsive">
    <div class="panel-heading">
      <h5>Inscriptos</h5>
    </div>
    <div class="panel-body">
      <div class="table-responsive">
        <table class="table table-striped">
          <tr>
            <th>Asistencia</th>
            <th>Nombre</th>
            <th>Teléfono</th>
            <th>Email</th>
            <th>Certificado médico</th>
          </tr>
          <% users.each do |inscription| -%>
            <tr>
              <td>
                <%= check_box_tag "user_attended#{inscription.id}", true, inscription.attended,
                  data: {
                    remote: true,
                    method: :post,
                    url: url_for(controller: :inscriptions, action: :attended, id: inscription.id)
                  }
                -%>
              </td>
              <td>
                <%= inscription.user.full_name %>
              </td>
              <td>
                <%= inscription.user.phone %>
              </td>
              <td>
                <%= inscription.user.email %>
              </td>
              <td>
                <%= check_box_tag "user_certificate#{inscription.user.id}", true, inscription.user.certificate,
                  data: {
                    remote: true,
                    method: :post,
                    url: url_for(controller: :users, action: :certificate, id: inscription.user.id)
                  }
                -%>
              </td>
            </tr>
          <% end -%>
        </table>
      </div>
    </div>
  </div>
<% end %>

<% if rookies.count > 0 %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h5>Pruebas</h5>
    </div>
    <div class="panel-body">
      <div class="table-responsive">
        <table class="table table-striped">
          <tr>
            <th>Asistencia</th>
            <th>Nombre</th>
            <th>Teléfono</th>
            <th>Email</th>
            <th>Notas</th>
          </tr>
          <% rookies.each do |rooky| -%>
            <tr>
              <td>
                <%= check_box_tag "rooky_attended#{rooky.id}", true, rooky.attended,
                  data: {
                    remote: true,
                    method: :post,
                    url: url_for(controller: :rookies, action: :attended, id: rooky.id)
                  }
                -%>
              </td>
              <td>
                <%= rooky.full_name %></b>
              </td>
              <td>
                <%= rooky.phone %>
              </td>
              <td>
                <%= rooky.email %>
              </td>
              <td>
                <%= rooky.notes %>
              </td>
            </tr>
          <% end -%>
        </table>
      </div>
    </div>
  </div>
<% end %>

app/views/shifts/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Modificar Clase</h4>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/shifts/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Clases</h4>
  </div>
  <div class="panel-body">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= link_to "Agregar una nueva Clase", new_shift_path, class: 'btn btn-primary' %>
      </div>
    </div>
    <div class="table-responsive">
      <table id="shifts-table" class="table table-striped table-bordered" cellspacing="0" width="100%" data-source="<%= shifts_path(format: :json) %>">
          <thead>
              <tr>
                  <th>Dia y hora</th>
                  <th>Cupo</th>
                  <th>Próxima</th>
                  <th>Anotados</th>
                  <th>Estado</th>
                  <th></th>
              </tr>
          </thead>
          <tbody>
          </tbody>
      </table>
    </div>
  </div>
</div>

app/views/shifts/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Nueva Clase</h4>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/shifts/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4><%= @shift.day_and_time %></h4>
  </div>
  <div class="panel-body">
    <p>
      <b>Cupo:</b>
      <%= @shift.max_attendants %>
    </p>

    <p>
      <b>Pr&oacute;xima clase:</b>
      <%= l(@shift.next_fixed_shift, :format => '%A, %e de %B %H:%M hs.') %>
    </p>

    <p>
      <b>Anotados:</b>
      <%= @shift.next_fixed_shift_count %>
    </p>

    <p>
      La inscripci&oacute;n est&aacute; <b><%= @shift.status %></b>
    </p>

    <p>
      La inscripci&oacute;n abre <b><%= @shift.open_inscription %> horas</b> antes
    </p>

    <p>
      La inscripci&oacute;n cierra <b><%= @shift.close_inscription %> horas</b> antes
    </p>

    <p>
      <b>Instructor:</b>
      <%= @shift.instructor.full_name %>
    </p>

    <p>
      <b>Disciplina:</b>
      <%= @shift.discipline.name %>
    </p>

    <p>
      <%= render partial: "user_list", locals: {users: @shift.next_fixed_shift_users, rookies: @shift.next_fixed_shift_rookies} %>
    </p>
  </div>
</div>