config/routes.rb
Nahual::Application.routes.draw do
  devise_for :users

  root :to => 'inscriptions#index'


  resources :disciplines do
    member do
      post 'disable_all'
      post 'enable_all'
    end
  end

  resources :users, :only => [:index, :destroy, :edit, :update] do
    resources :payments, :only => [:new, :create]
    collection do
      get 'credits', to: 'users#credits'
      post 'reset', to: 'users#reset'
      post 'set_reset', to: 'users#set_reset'
      get 'reset_search', to: 'users#reset_search'
      get 'stop_impersonating'
    end
    member do
      get 'impersonate'
      post 'certificate'
    end
  end

  resources :payments, only: [:edit, :update]

  resources :past_shifts, :only => [:index, :show]

  resources :shifts do
    collection do
      get 'next_class'
    end
  end

  resources :payments, :only => [:index, :destroy] do
    collection do
      get 'total_payments', to: 'payments#total_payments'
    end
  end

  resources :rookies do
    collection do
      get 'new_in_shift/:shift_id', to: 'rookies#new_in_shift', as: 'new_in_shift'
    end
    member do
      post 'attended'
    end
  end

  resources :stats, :only => [:index] do
    collection do
      get 'month_inscriptions_chart', to: 'stats#month_inscriptions_chart', as: 'month_inscriptions_chart'
    end
  end

  resources :inscriptions
  post 'incriptions/:id/attended', to: 'inscriptions#attended'

  resources :messages
  resources :packs

  get 'check_pending_messages', to: 'application#check_pending_messages'
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user

  before_update :clean_reset_date
  before_destroy :validate_no_used_credit

  after_commit :update_credit

  validates_presence_of :month_year, :amount, :credit, :user, :credit_start_date, :credit_end_date
  validates_numericality_of :credit, greater_than_or_equal_to: ->(p) { p.used_credit.to_i }
  validate :valid_date_range_required

  audited

  def self.filter_by_dates(date_from, date_to)
    if date_from.present? && date_to.present?
      from = Chronic.parse(date_from, :endian_precedence => [:little, :middle])
      to = Chronic.parse(date_to, :endian_precedence => [:little, :middle])
      Payment.joins(:user).where(created_at: from..to)
    else
      Payment.joins(:user)
    end
  end

  def self.total_payments(date_from, date_to)
    self.filter_by_dates(date_from, date_to).select('SUM(amount) as total_payments').first.total_payments rescue 0
  end


private

  def clean_reset_date
    self.reset_date = nil
  end

  def update_credit
    self.user.update_credits!
  end

  def valid_date_range_required
    errors.add(:base, "La fecha de vencimiento de créditos debe ser mayor que la fecha de comienzo de validez de los créditos") if (credit_start_date > credit_end_date)
  end

  def validate_no_used_credit
    if (used_credit.to_i != 0)
      errors.add(:base, "El Pago no puede ser borrado porque ya se han usado créditos del mismo")
      return false
    end
  end


end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def index
    respond_to do |format|
      format.html

      format.json {
        if params[:user_id].present?
          render json: UserPaymentDatatable.new(view_context)
        else
          render json: PaymentDatatable.new(view_context)
        end
      }

      format.xlsx {
        @payments = Payment.filter_by_dates(params[:date_from], params[:date_to])
        render xlsx: 'excel', filename: "la_tribu-pagos-#{Date.today.strftime}.xlsx"
      }
    end
  end

  def edit
    @payment = Payment.find(params[:id])
    @user = @payment.user
  end

  def update
    @payment = Payment.find(params[:id])
    @user = @payment.user
    params = payment_params
    month = params.delete(:month)
    year = params.delete(:year)
    if @payment.update_attributes({
        month_year: Chronic.parse("1 #{month} #{year}"),
        credit_start_date: params[:credit_start_date],
        credit_end_date: params[:credit_end_date],
        amount:  params[:amount],
        credit: params[:credit],
      })
      redirect_to new_user_payment_path(@payment.user_id), notice: "El Pago de #{@payment.user.full_name} fue modificado correctamente."
    else
      flash[:error] = @payment.errors.to_a.join("<br />")
      render action: "edit"
    end

  end

  def total_payments
    total = Payment.total_payments(params[:date_from], params[:date_to])
    render json: { total: ActionController::Base.helpers.number_to_currency(total) }
  end

  def new
    @user = User.find(params[:user_id])
    @payment = @user.payments.build
  end

  def create
    params = payment_params
    @user = User.find(params[:user_id])
    month = params.delete(:month)
    year = params.delete(:year)
    params = params.merge( {:month_year => Chronic.parse("1 #{month} #{year}")} )
    @payment = Payment.new(params)
    if @payment.save
      redirect_to new_user_payment_url(@user), notice: 'Nuevo Pago creado.'
    else
      flash[:error] = @payment.errors.to_a.join("<br />")
      render action: "new"
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment = Payment.find(params[:id])
    if @payment.destroy
      flash[:success] = "El Pago de #{@payment.user.full_name} fue eliminado correctamente."
    else
      flash[:error] = @payment.errors.to_a.join("<br />")
    end
    redirect_to new_user_payment_path(@payment.user_id)
  end

  private

  def payment_params
    params.require(:payment).permit(:user_id, :amount, :credit, :month, :year, :credit_start_date, :credit_end_date)
  end

end

app/views/payments/_edit_form.html.erb
<%= simple_form_for [@payment] do |f| %>

  <div class="form-inline">
    <label class="control-label col-md-12 no-padding" style="margin-bottom: 10px;">
      Período de validez de los créditos
    </label>

    <div class='col-md-6' style="margin-bottom: 20px;">
      <div class="form-group">
        <label for="date-from">Desde</label>
        <div class='input-group date' id='date-from-credit' style="width: 350px;">
          <input type='text' class="form-control" readonly="readonly" name="payment[credit_start_date]" id="date-from" value="<%= @payment.credit_start_date %>" />
          <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>
    </div>

    <div class='col-md-6' style="margin-bottom: 20px;">
      <div class="form-group">
        <label for="date-to">Hasta</label>
        <div class='input-group date' id='date-to-credit' style="width: 350px;">
          <input type='text' class="form-control" readonly="readonly" name="payment[credit_end_date]" id="date-to" value="<%= @payment.credit_end_date %>" />
          <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>
    </div>

    <div class='col-md-12' style="margin-bottom: 20px;">
      <label for="payment-month">Mes</label>
      <%= f.input :month, collection: t('date.month_names').compact.each_with_index.collect { |m, i| [ m.capitalize, Date::MONTHNAMES[i+1].downcase ] }, selected:  Date::MONTHNAMES[Time.now.month].downcase, label: false  %>
      <%= f.input :year, collection: Time.now.year..Time.now.year + 2, selected: Time.now.year, label: false %>
    </div>

  </div>

  <%= f.input :current_credit, label: "Crédito actual", input_html: { value: "#{@user.credit}", style: "width: 100px;", disabled: true } %>
  <%= f.input :amount, input_html: { style: "width: 100px;" } %>
  <%= f.input :credit, input_html: { style: "width: 100px;" }, hint: 'No puede ser menor al crédito ya usado' %>
  <%= f.input :used_credit, label: "Crédito usado", input_html: { value: "#{@payment.used_credit}", style: "width: 100px;", disabled: true } %>


  <%= f.submit 'Guardar', data: { disable_with: "Procesando..." }, class: "btn btn-primary" %>
  <%= link_to "Volver", new_user_payment_url(@user), class: "btn btn-default" %>
<% end %>

app/views/payments/_form.html.erb
<%= simple_form_for [@user, @payment] do |f| %>

  <%= f.hidden_field :user_id, :value => @user.id, id: :payment_user_id %>

  <div class="form-inline" style="margin-bottom: 20px;">
    <label for="active-pack">Pack de clases activo</label>
    <input type='text' class="form-control" readonly="readonly"  id="active-pack" value="<%= @user.pack.try(:name) || 'Ninguno' %>" />
    <input type="button" value="Cambiar" class="btn btn-primary" id="change-pack" />
  </div>

  <div class="form-inline">
    <label class="control-label col-md-12 no-padding" style="margin-bottom: 10px;">
      Período de validez de los créditos
    </label>

    <div class='col-md-6' style="margin-bottom: 20px;">
      <div class="form-group">
        <label for="date-from">Desde</label>
        <div class='input-group date' id='date-from-credit' style="width: 350px;">
          <input type='text' class="form-control" readonly="readonly" name="payment[credit_start_date]" id="date-from" />
          <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>
    </div>

    <div class='col-md-6' style="margin-bottom: 20px;">
      <div class="form-group">
        <label for="date-to">Hasta</label>
        <div class='input-group date' id='date-to-credit' style="width: 350px;">
          <input type='text' class="form-control" readonly="readonly" name="payment[credit_end_date]" id="date-to" />
          <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>
    </div>

    <div class='col-md-12' style="margin-bottom: 20px;">
      <label for="payment-month">Mes</label>
      <%= f.input :month, collection: t('date.month_names').compact.each_with_index.collect { |m, i| [ m.capitalize, Date::MONTHNAMES[i+1].downcase ] }, selected:  Date::MONTHNAMES[Time.now.month].downcase, label: false  %>
      <%= f.input :year, collection: Time.now.year..Time.now.year + 2, selected: Time.now.year, label: false %>
      &nbsp;<i>Esto es solo para el reseteo <b>manual</b> de creditos</i>
    </div>

  </div>

  <%= f.input :current_credit, label: "Crédito actual", input_html: { value: "#{@user.credit}", style: "width: 100px;", disabled: true } %>
  <%= f.input :amount, input_html: { style: "width: 100px;" } %>
  <%= f.input :credit, input_html: { style: "width: 100px;" } %>

  <%= f.submit 'Guardar', data: { disable_with: "Procesando..." }, class: "btn btn-primary" %>
  <%= link_to "Volver", users_url, class: "btn btn-default" %>
<% end %>

<div id="payment-history-panel" class="panel panel-default">
  <div class="panel-heading">Historial de Pagos</div>
  <div class="table-responsive">
    <table id="user-payments-table" class="table table-striped" cellspacing="0" width="100%" data-source="/payments?user_id=<%= @user.id %>.json">
        <thead>
        <tr>
          <th>Fecha de pago</th>
          <th>Vencimiento de créditos</th>
          <th>Monto</th>
          <th>Crédito</th>
          <th>Crédito usado</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
  </div>
</div>

<div id="packModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" id="error" style="display: none; color: red;">
        Hubo un error al tratar de guardar el pack, por favor vuelva intentar.
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>Pack de clases activo para <%= @user.full_name %></h4>
        </div>
        <div class="panel-body">
            <div class="form-inline">
              <div class="form-group select optional">
                <%=
                  select_tag(
                        'pack_id',
                        options_from_collection_for_select(Pack.all, "id", "name", @user.pack.try(:id)),
                        include_blank: "Ninguno",
                        id: 'select-pack-modal',
                        class: 'select optional form-control',
                        style: "width: 300px;"
                    )
                %>
              </div>
              <%= link_to 'Guardar', '#', class: 'btn btn-primary', id: 'save-pack-modal' %>
              <%= link_to 'Cancelar', '#', class: 'btn btn-default', id: 'cancel-pack-modal' %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/payments/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Modificar Pago de <%= @user.full_name %></h4>
    </h4>
  </div>
  <div class="panel-body">
    <%= render 'edit_form' %>
  </div>
</div>

app/views/payments/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Filtrar pagos</h4>
  </div>
  <div class="panel-body">
    <%= form_tag(payments_path(format: :xlsx), method: "get", id: "payments_form") do %>
      <div class="container-fluid">
        <div class='col-md-3'>
          <div class="form-group">
            <label for="date-from">Desde</label>
            <div class='input-group date' id='date-from-comp'>
              <input type='text' class="form-control" name="date_from" id="date-from" />
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
          </div>
        </div>
        <div class='col-md-3'>
          <div class="form-group">
            <label for="date-to">Hasta</label>
            <div class='input-group date' id='date-to-comp'>
              <input type='text' class="form-control" name="date_to" id="date-to" />
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
          </div>
        </div>
        <div class='col-md-3 filter-buttons-div'>
          <%= button_tag("Buscar", id: "payments-search-button", class: "btn btn-primary", :type => 'button') -%>
          <%= button_tag("Exportar", id: "payments-export-button", class: "btn btn-default", :type => 'button') -%>
        </div>
      </div>
    <% end %>

    <div id="payment-panel" class="panel panel-default">
      <div class="panel-heading">Pagos</div>
      <div class="table-responsive">
        <table id="payments-table" class="table table-striped" cellspacing="0" width="100%" data-source="/payments.json">
          <thead>
          <tr>
            <th>Fecha de pago</th>
            <th>Cliente</th>
            <th>Monto</th>
            <th>Crédito</th>
            <th>Mes acreditado</th>
          </tr>
          </thead>
          <tbody>
          </tbody>
          <tfoot>
            <tr>
              <td colspan="5" class="text-right"><strong>Total pagado en el período: <span id="total-payments"></span></strong></td>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>

  </div>
</div>

app/views/payments/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Registrar Pago de <%= @user.full_name %></h4>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>